# Generated by Django 2.1.7 on 2020-04-04 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20200404_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
