# Generated by Django 2.1.7 on 2020-04-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20200404_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=32)),
                ('books_title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=16)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'それ以外')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='poet',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
