# Generated by Django 2.1.7 on 2020-04-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_auto_20200406_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'それ以外')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
