# Generated by Django 2.1.7 on 2020-04-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
